### ISSUE TITLE
Add a tag for symfony 3 support

### ISSUE THREAD

**Issue by benji07** [sonata-project/SonataIntlBundle#100]
Maybe you can create a new tag (the last release is 25 commit away)

**Comment by tyx** [comment]
:+1:

**Comment by Spea** [comment]
That would be awesome :+1:

**Comment by OskarStark** [comment]
reminder @Soullivaneuh

**Comment by korotovsky** [comment]
ping. 

This bundle is a last one in our project that doesn't have tag for SF3 :(

**Comment by core23** [comment]
Created a new tag 2.2.4
