### ISSUE TITLE
Cache number and date formatters?

### ISSUE THREAD

**Issue by asprega** [sonata-project/SonataIntlBundle#104]
Hi everybody.

While debugging a page with a complex layout (lots of dates and currency values in a big table) I noticed that a big part of the overhead is due to construction of \NumberFormatters (and \IntlDateFormatters). A solution would be to cache them in the `getFormatter` method, keyed by `$culture` and `$style`. The problem is that `$attributes` and `$textAttributes` would be set again and again on the same instance, instead of setting them every time on a new instance. The potential problem I see with that, is be if somebody somehow extended e.g. the `NumberHelper` and cached the formatter instance returned by the protected `getFormatter` method. This way its attributes would change without the extending class knowing that. If we see it strictly enough, this is a BC break. On the other hand, please look at the provided screenshot to see what's the performance impact. Just to get a sense, caching the number formatter in my case improved by 19% my page load time.

I guess I'm just asking whether you think caching that way is acceptable. If positive, I can do a pull request. What do you think?

<img width="749" alt="schermata 2016-01-05 alle 22 10 37" src="https://cloud.githubusercontent.com/assets/2210656/12127743/3bdf2936-b3f9-11e5-8bfa-67ed51bc3de5.png">
<img width="728" alt="schermata 2016-01-05 alle 22 20 31" src="https://cloud.githubusercontent.com/assets/2210656/12127966/943aa352-b3fa-11e5-8b34-a1e5bbebada2.png">

**Comment by OskarStark** [comment]
@rande can you please give some feedback?

**Comment by rande** [comment]
I think the cache option can be optional; and disable by default. So the code will be BC

**Comment by OskarStark** [comment]
sounds good

@asprega are you willing to provide a PR?

**Comment by OskarStark** [comment]
@asprega will you work on a PR?

**Comment by Soullivaneuh** [comment]
Close as no answer.

Also please see https://github.com/sonata-project/SonataIntlBundle/issues/182.
