### ISSUE TITLE
Region ignored in language filter

### ISSUE THREAD

**Issue by Bullettoothtobi** [sonata-project/SonataIntlBundle#112]
There is a bug in LocaleHelper.php :
`$name = Intl::getLanguageBundle()->getLanguageName($codes[0], isset($codes[1]) ? $code[1] : null, $locale ?: $this->localeDetector->getLocale());`

Parameter $code[1] should be $codes[1].
Right now the region is being ignored.

**Comment by greg0ire** [comment]
I think you are right. Would you kindly make a pull request ?

**Comment by Bullettoothtobi** [comment]
sure

**Comment by greg0ire** [comment]
Bonus points if it comes with tests :)
