### ISSUE TITLE
Allow Twig 2 

### ISSUE THREAD

**Issue by ruudk** [sonata-project/SonataIntlBundle#147]
Would be great if Twig 2 could be supported :)

**Comment by greg0ire** [comment]
It is.

**Comment by ruudk** [comment]
Ah, I see, master is compatible with Twig 2.... 

I checked the latest release and it wasn't: https://packagist.org/packages/sonata-project/intl-bundle

**Comment by greg0ire** [comment]
No, not master, the stable branch is. But there has been no release since then, I asked for one.

**Comment by greg0ire** [comment]
See #146

**Comment by ruudk** [comment]
Sorry :) Thanks for clarification!

**Comment by greg0ire** [comment]
No problem ;)
