### ISSUE TITLE
Conflict issue with user-bundle

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataIntlBundle#181]
I'm creating this issue in order to track the fact exposed at [this comment](https://github.com/sonata-project/SonataIntlBundle/pull/162#issuecomment-323009241) from @OskarStark at #162.

**Comment by phansys** [comment]
The tag [`2.3.2`](https://github.com/sonata-project/SonataIntlBundle/blob/2.3.2/composer.json#L37) already have the changes introduced at #162, but I am not able to install this package alongside `sonata-project/user-bundle: 4.0@dev`. I pushed a branch `sonata_conflicts` to my fork of  `symfony/symfony-standard` in order to expose this issue: https://github.com/phansys/symfony-standard/blob/sonata_conflicts/composer.json#L23-L27.
Can somebody give me any clue about this scenario?
Thank you in advance.

**Comment by core23** [comment]
cc @Soullivaneuh

**Comment by phansys** [comment]
It seems weird to me, since the conflicting constraint [`"sonata-project/user-bundle": "<2.0 || >=5.0"`](https://github.com/sonata-project/SonataIntlBundle/blob/2.3.2/composer.json#L37) should NOT match `4.x-dev`, as you can check at [https://semver.mwl.be](https://semver.mwl.be/#?package=sonata-project%2Fuser-bundle&version=%3C2.0%20%7C%7C%20%3E%3D5.0&minimum-stability=stable).

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/SonataIntlBundle/releases/tag/2.4.0

**Comment by phansys** [comment]
@Soullivaneuh, even with this release, I'm still not able to install these packages together. Could you please check with this `composer.json`:
```
{
    "require": {
        "sonata-project/intl-bundle": "^2.4",
        "sonata-project/user-bundle": "4.0@dev"
    }
}
```

```$ composer --version
Composer version 1.6-dev (bfed974ae969635e622c4844e5e69526d8459baf) 2017-11-03 22:23:28
```
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package sonata-project/user-bundle 4.0@dev exists as sonata-project/user-bundle[2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.x-dev, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.3.0, 3.4.0, 3.5.0, 3.x-dev, dev-master, 4.x-dev] but these are rejected by your constraint.

```

**Comment by Soullivaneuh** [comment]
Your log show it's a user-bundle issue AFAIK.

NB: You may try with `4.x-dev`.

**Comment by phansys** [comment]
I've tried with all possible variants, the result is the same. Even, I'm pretty sure that composer doesn't read "-dev" as a [stability flag](https://getcomposer.org/doc/04-schema.md#minimum-stability).
Here you are the output for some constraint variants:
**`"4.x-dev"`**:
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/intl-bundle ^2.4 -> satisfiable by sonata-project/intl-bundle[2.4.0].
    - don't install sonata-project/user-bundle 4.x-dev|install sonata-project/user-bundle dev-master
    - sonata-project/user-bundle dev-master conflicts with sonata-project/intl-bundle[2.4.0].
    - Installation request for sonata-project/user-bundle 4.x-dev -> satisfiable by sonata-project/user-bundle[4.x-dev].

```
**`"4.x@dev"`**:
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/intl-bundle ^2.4 -> satisfiable by sonata-project/intl-bundle[2.4.0].
    - don't install sonata-project/user-bundle 4.x-dev|install sonata-project/user-bundle dev-master
    - sonata-project/user-bundle dev-master conflicts with sonata-project/intl-bundle[2.4.0].
    - Installation request for sonata-project/user-bundle 4.x@dev -> satisfiable by sonata-project/user-bundle[4.x-dev].

```

**Comment by Soullivaneuh** [comment]
Surely related to this: https://github.com/sonata-project/SonataIntlBundle/blob/82d3e586b30aeea31c5a93c673f0b4b4eebbf7b8/composer.json#L37

But I don't know such more ATM. I'm re-opening.

**Comment by phansys** [comment]
Of course @Soullivaneuh, I've mentioned that on [a previous comment](https://github.com/sonata-project/SonataIntlBundle/issues/181#issuecomment-344046608), but that constraint should not conflict these versions AFAIK.

**Comment by Soullivaneuh** [comment]
Maybe it works not very well with dev versions. Maybe we should remove the `|| >=5.0` part. cc @sonata-project/contributors

**Comment by phansys** [comment]
In fact, I am currently using a fork with that part removed https://github.com/phansys/SonataIntlBundle/blob/7b71381c531caa8a92e7723ea191f7a03bb02431/composer.json#L36-L38;
but I think it could be a issue with the resolution performed by Composer around `conflict` constraints.

**Comment by nico-dangerous** [comment]
Hi, 
I don't understand why we have to wait for a potential 6.0.0 version of Sonata User bundle.
With conflict >= 5.0.0, we can't even use it with the dev version of user bundle.

Is anyone from sonata floowing this ?

**Comment by jordisala1991** [comment]
Do you know that user-bundle is already stable on 4.0? Try 4.0.0
