### ISSUE TITLE
Strict type checking introduced in 2.6.0 throws error on Doctrine decimal type

### ISSUE THREAD

**Issue by krzyc** [sonata-project/SonataIntlBundle#256]
### Environment
PHP 7.2
Symfony 4.2.8
sonata-project/admin-bundle 3.48.1
sonata-project/intl-bundle 2.6.0

## Subject
After upgrading from 2.5.0 to 2.6.0 field that uses Doctrine DECIMAL type, which is implemented as PHP string, throws error like:
NumberFormatter::formatCurrency() expects parameter 1 to be float, string given
This is because of strict type checking.

## Steps to reproduce
Try to format Doctrine DECIMAL type as currency.

## Expected results
Keep compatibility with previous behavior by removing strict type checking or, better, by making sure that value is passed as accepted type - float for decimal.

## Actual results
Exception NumberFormatter::formatCurrency() expects parameter 1 to be float, string given:
 in vendor/sonata-project/intl-bundle/src/Templating/Helper/NumberHelper.php (line 162)
in vendor/sonata-project/intl-bundle/src/Templating/Helper/NumberHelper.php->formatCurrency (line 162)
in vendor/sonata-project/intl-bundle/src/Twig/Extension/NumberExtension.php->formatCurrency (line 83)

**Comment by greg0ire** [comment]
> by making sure that value is passed as accepted type - float for decimal.

Can you please create a PR that does this?
