### ISSUE TITLE
Deprecate this bundle

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataIntlBundle#280]
There are good and better maintained replacements on the market:

- https://github.com/twigphp/intl-extra
- https://github.com/symfony/polyfill-intl-icu

Refs #182

**Comment by core23** [comment]
cc @sonata-project/contributors

**Comment by greg0ire** [comment]
I'm all for it! There are some Sonata packages that depend on this:

- `sonata-project/admin-bundle`
- `sonata-project/ecommerce`
- `sonata-project/media-bundle`
- `sonata-project/news-bundle`
- `sonata-project/timeline-bundle`

**Comment by core23** [comment]
The only thing that we still need is the locale detector that updates the user entity.

**Comment by franmomu** [comment]
Trying to get rid of this bundle in TimelineBundle, the problem is that [twig/intl-extra has `"symfony/intl": "^4.3|^5.0"`](https://github.com/twigphp/intl-extra/blob/2.x/composer.json#L19) requirement and we have in Travis [one job with `symfony/symfony: 3.4.*`](https://github.com/sonata-project/SonataIntlBundle/blob/2.x/.travis.yml#L47).

**Comment by greg0ire** [comment]
I think it's ok to drop 3.4, we are only supposed to support one LTS at a time: https://github.com/sonata-project/SonataIntlBundle/blob/2.x/CONTRIBUTING.md#dependency-changes

**Comment by XWB** [comment]
@core23 Unfortunately `twigphp/intl-extra` only provides Twig filters for number and date formatting. AFAIK Symfony has no built in services to achieve something like:

```php
use Sonata\IntlBundle\Templating\Helper\DateTimeHelper;

class MyClass
{
    private $dateTimeHelper;

    public function __construct(DateTimeHelper $dataTimeHelper)
    {
        $this->dateTimeHelper = $dataTimeHelper;
    }

    public function myFunction(string $format)
    {
        // to something with $this->dateTimeHelper
    }
}
```

**Comment by core23** [comment]
> @core23 Unfortunately `twigphp/intl-extra` only provides Twig filters for number and date formatting. AFAIK Symfony has no built in services to achieve something like:
> 
> ```
> use Sonata\IntlBundle\Templating\Helper\DateTimeHelper;
> 
> class MyClass
> {
>     private $dateTimeHelper;
> 
>     public function __construct(DateTimeHelper $dataTimeHelper)
>     {
>         $this->dateTimeHelper = $dataTimeHelper;
>     }
> 
>     public function myFunction(string $format)
>     {
>         // to something with $this->dateTimeHelper
>     }
> }
> ```

Maybe we could move from this bundle to the symfony bundle?

**Comment by VincentLanglet** [comment]
Shouldn't the readme be updated if this repository is deprecated ?

**Comment by core23** [comment]
> Shouldn't the readme be updated if this repository is deprecated ?

Can you do this @VincentLanglet

**Comment by VincentLanglet** [comment]
Yes I can @core23 
https://github.com/sonata-project/SonataIntlBundle/pull/296

But I also saw that the deprecated packages had this
![image](https://user-images.githubusercontent.com/9052536/76173579-db4ade80-61a0-11ea-8ca3-0ac1e8592f2c.png)

I don't have the right to modify the description.

**Comment by greg0ire** [comment]
Thanks for pointing it out. Looks like I have the necessary permissions to do this, I just changed the description.

**Comment by VincentLanglet** [comment]
> Thanks for pointing it out. Looks like I have the necessary permissions to do this, I just changed the description.

Can you do the same for https://github.com/sonata-project/SonataCacheBundle and https://github.com/sonata-project/SonataEasyExtendsBundle

**Comment by greg0ire** [comment]
Done (TIL the cache bundle is deprecated :sweat_smile:)

**Comment by VincentLanglet** [comment]
Cf https://github.com/sonata-project/SonataIntlBundle/pull/300#issuecomment-635904647
