### ISSUE TITLE
Wrong year?

### ISSUE THREAD

**Issue by mjuchli** [sonata-project/SonataIntlBundle#48]
Hi,

//date variable set to 01.01.1955
Somehow strange but with {{ dateobject | format_date('MMMM Y', 'de', 'Europe/Zurich') }} will give me "Januar 1954" (wrong year!). 01.01.1955 is not the only one, for my example 01.01.1960 as well (->1959).

The thing is that this happens only on sometimes (dont see a cycle yet) and when i change the day to 04.01.1960 it'll work (01., 02., 03. not).

Any ideas?

Best,
Marc

**Comment by fliespl** [comment]
Know it's pretty late, but I have replicated this problem today (date with 2018-12-31 get shown as 2019-12-31). It's not an issue with the code, but Intl pattern provided.

Y = year of "Week of Year"

Changing pattern to "MMMM yyyy" fixes wrong year.

**Comment by OskarStark** [comment]
Can you provide a PR?

**Comment by fliespl** [comment]
@OskarStark like I mentioned - error was in user configuration - not code itself :)
