### ISSUE TITLE
Set default date format

### ISSUE THREAD

**Issue by 76200** [sonata-project/SonataIntlBundle#50]
Is there any chance to set default date format for format_date filter?

**Comment by edrush** [comment]
Hi,

I'm also searching for such an option - any news or plans on that?

**Comment by greg0ire** [comment]
Just to be clear, you would like to be able to get the same default format for all users, regardless of their locale?

**Comment by jlamur** [comment]
The [Intl bundle documentation](https://sonata-project.org/bundles/intl/master/doc/reference/datetime.html) says:

> By default the helper methods use the current user’s locale to display information. Of course this behavior can be controlled from within the template by providing extra parameters :
> 1. pattern : the pattern to use to render the date
> 2. the locale
> 3. the timezone to use if date is not a `DateTime` instance
> 4. (`format_date` and `format_datetime` only) the date type to use if no pattern were provided: the given value must be one of `\IntlDateFormatter::{SHORT, MEDIUM, LONG, FULL}` or `null` (if `null`, defaults to `\IntlDateFormatter::MEDIUM`)
> 5. (`format_time` and `format_datetime` only) the time type to use if no pattern were provided: the given value must be one of `\IntlDateFormatter::{SHORT, MEDIUM, LONG, FULL}` or `null` (if `null`, defaults to `\IntlDateFormatter::MEDIUM`)
> ```
> {{ date_time_object | format_date(null, 'fr', 'Europe/Paris', constant('IntlDateFormatter::LONG')) }} => '1 février 2011'
> {{ date_time_object | format_time(null, 'fr', 'Europe/Paris', constant('IntlDateFormatter::SHORT')) }} => '19:55'
> {{ date_time_object | format_datetime(null, 'fr', 'Europe/Paris', constant('IntlDateFormatter::LONG'), constant('IntlDateFormatter::SHORT')) }} => '1 février 2011 19:55'
> {{ date_time_object | format_[date|time|datetime]('dd MMM y G', 'fr', 'Europe/Paris') }} => '01 février 2011 ap. J.-C.'
> ```

If I understand correctly, this issue is about overriding the 4th or 5th parameters default values (i.e. `\IntlDateFormatter::MEDIUM`)?

**Comment by edrush** [comment]
Right, in my case it's just about datetype and timetype for rendering date times. Actually the time type for rendering date times defaults to \IntlDateFormatter::MEDIUM ([in DateTimeHelper](https://github.com/sonata-project/SonataIntlBundle/blob/2.x/Templating/Helper/DateTimeHelper.php#L89)), so all date times will render seconds (if not configured otherwise). 

For my application I would like to default to _not_ render seconds.

**Comment by jlamur** [comment]
I'm not sure if it's good idea to let users customize these default values. Anyway, you can create your own twig filter and/or override intl templates. It should cover all possible cases.

**Comment by edrush** [comment]
Thanks, I tried to override the datetime template by configuring the following but it seems to be ignored (or overriden by SonataIntlBundle?):

sonata_doctrine_orm_admin:
->    templates:
->->        types:
->->->            show:
->->->->                datetime: MyBundle:CRUD:show_datetime.html.twig

**Comment by edrush** [comment]
Sorry, I confused list and show - thank you @jlamur!

**Comment by greg0ire** [comment]
You should learn about markdown

**Comment by edrush** [comment]
True.
