### ISSUE TITLE
Twig filter format_datetime problème if date is near the end of the year

### ISSUE THREAD

**Issue by JoydS** [sonata-project/SonataIntlBundle#65]
Hello,
I have an issue with format_datetime when I have a datetime like this one : 
>2013-12-30 11:23:55

and doing a 
>{{ date | format_datetime('d MMMM YYYY à HH:mm:ss', 'fr') }}

It shows me : 
>30 décembre 2014 à 11:23:55

So one year later...
I tried with the date 2013-12-29 11:23:55 and it seems to not have a problem with this, so I think it's when the date is after the 30 december.

The problem seems to appear on this file : 
>DateTimeHelper line 140 when "return $this->fixCharset($formatter->format((int) $date->format('U')));" is called.

The problem seems to appear with this call specifically : 
>$formatter->format((int) $date->format('U'))

Sincerly,

Joyd.

**Comment by Soullivaneuh** [comment]
@JoydS Feel free to make a PR about it if you think documentation is not clear enough. :+1: 

Closing this issue as it's resolved.
