### ISSUE TITLE
Delete tag v1.0.0

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataIntlBundle#70]
@rande I think this tag could be deleted.

It doesn't exists on packagist: https://packagist.org/packages/sonata-project/intl-bundle

**Comment by Soullivaneuh** [comment]
ping @rande :-)

**Comment by OskarStark** [comment]
:+1:  for deletion!

**Comment by pulzarraider** [comment]
:-1: The git tags should never be deleted. The reason why it's not on packagist is that the version 1.0.0 does not contains the composer.json file. Nonexistence in thrid party system is not good reason for deleting the tag.

Same problem have other git repos. For example [Twig](https://packagist.org/packages/twig/twig). There is no version lower than `1.3.0` in packagist, but [they exists in the git](https://github.com/twigphp/Twig/tree/v1.2.0).
