### ISSUE TITLE
Add support for NumberFormatter symbol parameter

### ISSUE THREAD

**Issue by ste93cry** [sonata-project/SonataIntlBundle#72]
Currently there is no way to change symbol attributes using the `number_format_*` methods in Twig templates. This feature can be useful in various cases, for example when the user wants to change the thousand separator or the decimal separator. OroCRM properly implemented this feature in their [LocaleBundle](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/LocaleBundle/Formatter/NumberFormatter.php), would it be possible to add it to SonataIntlBundle too?

**Comment by Soullivaneuh** [comment]
Feel free to make a PR. :+1: 

With concrete samples, before / after etc...

**Comment by ste93cry** [comment]
Think PR will be break compatibility for sure because it introduces a new parameter in all Twig filters. Is this ok? We could add the parameter to the end of the list instead of before the `locale` argument, but it wouldn't be so nice.

    public function formatDecimal($number, array $attributes = array(), array $textAttributes = array(), $locale = null)

would be

    public function formatDecimal($number, array $attributes = array(), array $textAttributes = array(), symbolAttributes = array(), $locale = null)

**Comment by Soullivaneuh** [comment]
Yes I understand the local.

Maybe we could find another way to keep bc like a new method with old one deprecation.

If not, this feature will be for next major version.

In any case, any PR is welcome.

**Comment by ste93cry** [comment]
I will try to work on a PR (I already overridden a few classes to support this feature in my project) when I have some spare time, but I'm not an expert of PRs so be patient

**Comment by Soullivaneuh** [comment]
> I saw Symfony couting the number of args in some cases to maintain BC break while attending a new major version. Maybe we could do the same?

I'm curious. Could you provide a code sample link of this?

**Comment by ste93cry** [comment]
[Here](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Validator/Validator/LegacyValidator.php) it is. As you can see from the comment, they use the func_num_args to support different function signatures and keep the compatibility with older versions.

**Comment by Soullivaneuh** [comment]
Seems to be a good alternative, let's try it.

Sullivan SENECHAL
Le 22 juil. 2015 20:11, "Stefano Arlandini" <notifications@github.com> a
écrit :

**Comment by ste93cry** [comment]
I've submitted a PR, although I noticed a few things that I have to fix before merging. Btw, if you want to do a code review and tell me what you think about how I tried to manage the BC it would be great

**Comment by OskarStark** [comment]
@ste93cry would be good if you could prefix your PR with ``[WIP]`` if you work on it

thank you! :+1:

**Comment by ste93cry** [comment]
@rande I don't want to sound rude, but can you please check my PR and eventually approve/disapprove it?
