### ISSUE TITLE
Decouple twig from templating

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataIntlBundle#76]
We should do something like in this PR https://github.com/symfony/symfony/pull/13354 for getting possiblilty execute twig filters withound depends on Templating.

**Comment by OskarStark** [comment]
would you provide a PR if you get a :+1: ?

ping @sonata-project/contributors 

I am :+1: :-1:  and don't know it this is needed

**Comment by Koc** [comment]
@OskarStark yes, I can contribute. But is there no way use the original intl extension https://github.com/twigphp/Twig-extensions/blob/master/lib/Twig/Extensions/Extension/Intl.php whithout writing new one?

**Comment by OskarStark** [comment]
ok, thank you for your feedback @Koc

**Comment by jordisala1991** [comment]
I dont know where is templating used on this bundle, can you please provide more info?

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataIntlBundle/blob/93362f15ed8c3d65018dc6f0cf434452745a0008/src/Templating/Helper/BaseHelper.php#L15

This is the only reference to templating

**Comment by OskarStark** [comment]
@Koc do want to proceed here?

**Comment by Koc** [comment]
I'm afraid that no, because we don't using Sonata admin almost 2 years. We switched to REST based api on backend + SPA based on VueJs on frontend,

**Comment by Koc** [comment]
updated: haven't noticet that this repository not about admin panel but about intl. 

This change would require BC break because parent class changed. Is it ok?
