### ISSUE TITLE
InvalidArgumentException in UserBasedTimezoneDetector.php line 36

### ISSUE THREAD

**Issue by milokmet** [sonata-project/SonataIntlBundle#97]
The error message clearly says:
> Argument 1 should be an instance of ``Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface`` or ``Symfony\Component\Security\Core\SecurityContextInterface"``

but the TokenStorageInteface is checked against: ``Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface;`` specified in use statemtns

**Comment by rande** [comment]
reverted the PR for now.

**Comment by davidromani** [comment]
Same problem to me
